name: Build and Deploy FinLearn
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      # https://github.com/actions/checkout
    - name: Checkout code 
      uses: actions/checkout@v2

      # https://github.com/actions/setup-node
    - name: Install Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Install NPM packages
      run: npm ci

    - name: Build project
      run: npm run build
    
      # https://github.com/actions/upload-artifact
    - name: Upload production build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Download artiface
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build